os:
  - linux
language: node_js
node_js:
#  - "iojs"
#  - "7"
  - "6"
addons:
  apt:
    packages:
      - oracle-java8-set-default
cache:
  directories:
    - $HOME/.m2
    - node_modules
before_install:
  - chmod +x test/*.sh
install:
  - npm install
  - npm install -g yo
  - npm link
  - test/generate.sh all-options
script:
  - npm test
  - jdk_switcher use oraclejdk8
  - mvn clean install -f angutest/pom.xml
