os:
  - linux
language: java
jdk:
    - oraclejdk8
node_js:
#  - "iojs"
#  - "7"
  - "6"
cache:
  directories:
    - $HOME/.m2
    - node_modules
before_install:
  - node -v
  - npm -v
  - java -version
  - mvn -v
  - chmod +x test/*.sh
install:
  - npm install
  - npm install -g yo
  - test/generate.sh all-options
script:
  - npm test
  - mvn clean install
