os:
  - linux
language: node_js
node_js:
  - "7"
  - "6"
addons:
  apt:
    packages:
      - oracle-java8-set-default
cache:
  directories:
    - $HOME/.m2
    - node_modules
env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
before_install:
  - chmod +x test/*.sh
install:
  - npm install
  - npm install -g yo
  - npm link
script:
  - npm test
  - test/generate.sh no-options $HOME/no-options && mvn clean install -f $HOME/no-options/pom.xml
  - test/generate.sh no-angular $HOME/no-angular && mvn clean install -f $HOME/no-angular/pom.xml
  - test/generate.sh all-options $HOME/all-options && mvn clean install -f $HOME/all-options/pom.xml
