# ----------------------------------------
# SPRING BOOT
# ----------------------------------------

# possibility to override every spring boot properties

# ----------------------------------------
# LOGGING
# ----------------------------------------

logging:
    path: ${filter.logging.path}

# ----------------------------------------
# APPLICATION
# ----------------------------------------

<%=name%>:<%if (angular && plugins.custo) { %>
    external-resources-directory: ${filter.clients.path} <% } %>
